# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0b1d58de18ea6621ae467bd4d7bcfa967d74e486a9667093c1838c0be6a37aa0f26987dccd386388ebc053e99e283cab3cc88f551c8467514c8ebbb526c34c

test:
  secret_key_base: 0785fd5744c69d33df9ffff48c964d78c387812b8ae43c005357b7d0bbb2991cdc4e77fdc9d4c454b4385ddbd26d498ec29fc293a7b92ef429b703fc26e7c405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
